[package]
name = "stbchat-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.11"
stblib = { path = "C:\\Users\\Julian\\Desktop\\stblib-rust" }
rustyline = "13.0.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.27"
rayon = "1.8.0"
fastrand = { version = "2.0.1", features = [] }
serde_json = "1.0.108"
owo-colors = "4.0.0-rc.1"
tokio = "1.35.0"
clap = { version = "4.4.11", features = ["derive"] }