[package]
name = "stbchat-rust"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.11"
stblib = "0.2.7"
rustyline = "13.0.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.29"
rayon = "1.8.0"
fastrand = { version = "2.0.1", features = [] }
serde_json = "1.0.108"
owo-colors = "4.0.0"

[profile.release]
opt-level = 'z'
strip = true
lto = true