[package]
name = "stbchat-rust"
version = "1.3.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = { version = "0.6.2", features = ["stbchat"] }
tokio = { version = "1.39.2", features = ["full"] }
reqwest = "0.12.5"
rustyline = "14.0.0"
serde = { version = "1.0.205", features = ["derive"] }
serde_yaml = "0.9.34"
serde_json = "1.0.122"
rayon = "1.10.0"
fastrand = { version = "2.1.0" }
owo-colors = "4.0.0"
eyre = "0.6.12"
lazy_static = "1.5.0"
rprompt = "2.1.1"
socket2 = "0.5.7"
dirs = "5.0.1"
futures = "0.3.30"
strip-ansi-escapes = "0.2.0"

[profile.release]
opt-level = 'z'
strip = true
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
