[package]
name = "stbchat-rust"
version = "1.3.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = { version = "0.5.13", features = ["stbchat"] }
tokio = { version = "1.36.0", features = ["full"] }
reqwest = "0.11.24"
rustyline = "13.0.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
serde_json = "1.0.114"
rayon = "1.9.0"
fastrand = { version = "2.0.1" }
owo-colors = "4.0.0"
eyre = "0.6.12"
lazy_static = "1.4.0"
rprompt = "2.1.1"
socket2 = "0.5.5"
dirs = "5.0.1"
futures = "0.3.30"
strip-ansi-escapes = "0.2.0"

[profile.release]
opt-level = 'z'
strip = true
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
