[package]
name = "stbchat-rust"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = { version = "0.5.2", features = ["stbchat"] }
tokio = { version = "1.36.0", features = ["full"] }
rustyline = "13.0.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.29"
serde_json = "1.0.108"
rayon = "1.8.1"
fastrand = { version = "2.0.1" }
owo-colors = "4.0.0"
eyre = "0.6.12"
lazy_static = "1.4.0"
rprompt = "2.1.1"
socket2 = "0.5.5"

[profile.release]
opt-level = 'z'
strip = true
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
