name: Clippy

on: [push, pull_request]

jobs:
  rust:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - run: sudo apt install pkg-config libdbus-1-dev -y && cargo build --all-features

      - run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - run: sudo apt install pkg-config libdbus-1-dev -y && cargo clippy -- -D warnings